name: just_audio
description: A feature-rich audio player for Flutter. Loop, clip and concatenate any sound from any source (asset/file/URL/stream) in a variety of audio formats with gapless playback.
version: 0.10.1
repository: https://github.com/ryanheise/just_audio/tree/minor/just_audio
issue_tracker: https://github.com/ryanheise/just_audio/issues
topics:
  - audio
  - sound
  - player
  - background
publish_to: 'none'

environment: { sdk: ^3.6.0 }

dependencies:
  async: ^2.11.0
  audio_session: ^0.1.23
  crypto: ^3.0.6
  flutter: { sdk: flutter }
  just_audio_platform_interface:
    git:
      url: https://github.com/kishan-dhankecha/just_audio.git
      ref: visualizer
      path: just_audio_platform_interface
  just_audio_web:
    git:
      url: https://github.com/kishan-dhankecha/just_audio.git
      ref: visualizer
      path: just_audio_web
  meta: ^1.15.0
  path: ^1.9.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  mockito: ^5.4.5
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        default_package: just_audio_web
