name: just_audio_example
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'

environment: { sdk: ^3.6.0 }

dependencies:
  audio_session: ^0.1.23
  flutter: { sdk: flutter }
  just_audio:
    path: ../../just_audio
  just_audio_background:
    path: ..
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - audio/
