name: just_audio_web
description: Web platform implementation of just_audio. This implementation is endorsed and therefore doesn't require a direct dependency.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_web
version: 0.4.13

publish_to: 'none'

environment: { sdk: ^3.6.0 }

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JustAudioPlugin
        fileName: just_audio_web.dart

dependencies:
  # just_audio_platform_interface: ^4.3.0
  just_audio_platform_interface:
    git:
      url: https://github.com/kishan-dhankecha/just_audio.git
      ref: visualizer
      path: just_audio_platform_interface
  flutter: { sdk: flutter }
  flutter_web_plugins: { sdk: flutter }
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
