name: just_audio_background
description: An add-on for just_audio that supports background playback and media notifications.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_background
version: 0.0.1-beta.14
topics:
  - audio
  - sound
  - player
  - background
publish_to: 'none'

environment: { sdk: ^3.6.0 }

dependencies:
  just_audio_platform_interface:
    git:
      url: https://github.com/kishan-dhankecha/just_audio.git
      ref: visualizer
      path: just_audio_platform_interface
  audio_service: ^0.18.16
  audio_session: ^0.1.23
  flutter: { sdk: flutter }
  flutter_web_plugins: { sdk: flutter }
  meta: ^1.15.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0

