name: just_audio_background
description: An add-on for just_audio that supports background playback and media notifications.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_background
version: 0.0.1-beta.17
publish_to: 'none'
topics:
  - audio
  - sound
  - player
  - background

environment:
  sdk: ^3.8.1

dependencies:
  # just_audio_platform_interface: ^4.5.0
  just_audio_platform_interface:
    git:
      url: https://github.com/kishan-dhankecha/just_audio.git
      ref: visualizer
      path: just_audio_platform_interface
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.16.0
  rxdart: ^0.28.0
  synchronized: ^3.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
