name: just_audio_platform_interface
description: A common platform interface for the just_audio plugin. Different platform implementations of just_audio should implement this interface.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.3.0

environment: { sdk: ^3.6.0 }

dependencies:
  flutter: { sdk: flutter }
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test: { sdk: flutter }
  mockito: ^5.4.5
